blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ ãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³
    url: https://github.com/hondouchi/todo_slackapp/discussions
    about: è³ªå•ã‚„ææ¡ˆã¯ãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³ã§
  - name: ğŸ“š ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ
    url: https://github.com/hondouchi/todo_slackapp/tree/main/docs
    about: ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆè¨­è¨ˆãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ
